import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/custom-components/header";
import Footer from "@/components/custom-components/footer";
import { DataProvider } from "@/providers/DataProvider";
import { ThemeProvider } from "@/components/theme-provider";
import { TicketProvider } from "@/providers/TicketProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="light">
          <DataProvider>
            <TicketProvider>
              <Header />
              {children}
              <Footer />
            </TicketProvider>
          </DataProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
